# Perchè numpy

Pur essendo un linguaggio "batteries included", python è un linguaggio che da solo non è adatto a performare dei task specifici proprio della data science. numpy è una libreria che ci consente di avere: 
- più velocità: gli algoritmi scritti in C che vengono eseguiti nell'ordine dei nanosecondi piuttosto che dei secondi
- meno cicli: numpy contiene molte funzioni che se implementate a mano porterebbero via molto tempo e cicli
- codice più chiaro

È possibile installarlo normalmente come libreria con `pip`. Ricordiamo di lavorare in un ambiente virtuale utilizzando il comando `virtualenv`.



`pip install numpy`

Il processo di installazione potrebbe essere più lungo del previsto, vista la quantità di dipendenze e la loro grandezza in termini di byte. Ad ogni modo, una volta installato numpy possiamo importarlo come una qualsiasi libreria:

In [2]:
import numpy as np

Notiamo che l'import seguito dalla parola chiave `as` è un _import nominale_, cioè semplicemente un import in cui diamo un nome diverso ad una certa libreria. Da questo punto in poi potremo usare numpy nella forma contratta "np".

La struttura dati principale di numpy è l'array. È diverso da una lista Python (più efficiente dal punto di vista dell'occupazione di memoria e della velocità di accesso ai dati) e sostanzialmente rappresenta una matrice, conservandone tutte le principali proprietà. In particolare la documentazione di numpy parla di `homogeneous multidimensional array`, vale a dire array:
- multidimensionale
- __omogeneo__
- indicizzato da una tupla di numeri non negativi 
- le cui dimensioni prendono il nome di __assi__

Inoltre spesso ci ri riferisce ad un array numpy come ad un ndarray (N-Dimensional Array). 

Si può creare un array in diversi modi in numpy.

Caratteristiche principali di un ndarray:
    - ndim -> numero di assi (dimensioni) dell'array
    - shape -> tupla che indica la dimensione dell'array
    - size -> numero totale di elementi di un array
    - dtype -> il tipo degli elementi di un array

In [6]:
a = np.array([2, 3, 4])
print(type(a))
print(a)
print(a.ndim)


a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print(a.ndim)
print("shape -> ", a.shape, type(a.shape))
print(a.size)
print(a.dtype)


a = np.array([[7, 8, 9], [3, 6, 9]], dtype=np.float32)
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[2 3 4]
1
[[1 2 3]
 [4 5 6]]
2
shape ->  (2, 3) <class 'tuple'>
6
int64
[[7. 8. 9.]
 [3. 6. 9.]]
float32


In [20]:

np.arange(10, 20).reshape(2, -1)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Altri metodi per creare un ndarray sono:
- arange (magari in combinazione con reshape)
- zeros
- ones
- empty
- full
- eye
- random.default_rng()

In [3]:
print(np.arange(1, 11).reshape(2, 5))
print(np.arange(1, 10, 3))


print(np.zeros((3,3)))

print(np.ones((3, 3)))

arr = np.empty((2, 3))
print(arr)

print(np.full((4, 4), 5))


print(np.eye(5, 5))

print(np.eye(5, 5, 1))

print(np.eye(5, 5, -1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 4 7]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [26]:
generator = np.random.default_rng()
print(generator.random((3, 3))) # rappresentazione di un'immagine RGB

[[0.35704283 0.33149881 0.87267428]
 [0.89625564 0.10149822 0.6006322 ]
 [0.67257161 0.3852029  0.37985452]]


Esempio: creare una matrice di numeri interi randomici

In [27]:
x = np.random.randint(10)
print(x)

2
