In [1]:
import numpy as np

a = np.random.randint(1, 3, (3, 4))
b = np.random.randint(1, 3, (3, 4))
c = np.random.randint(1, 3, (3, 4))

print(a)
print(b)
print(c)



[[2 2 1 2]
 [2 1 1 2]
 [2 1 2 1]]
[[2 2 2 2]
 [1 1 2 1]
 [2 1 2 1]]
[[1 2 1 2]
 [1 1 2 2]
 [1 1 1 1]]


È possibile usare operatori aritmetici fra array. Le regole di precedenza sono quelle classiche per cui una moltiplicazione viene eseguita prima di una somma. Gli operatori aritmetici operano _elementwise_, ovvero elemento per elemento. Ergo: 
- `+` fa la somma di tutti gli elementi dei due operandi creando una nuova matrice
- `-` fa la differenza di tutti gli elementi dei due operandi creando una nuova matrice
- `*` fa la moltiplicazione di tutti gli elementi dei due operandi creando una nuova matrice
- `/` fa la divisione di tutti gli elementi dei due operandi creando una nuova matrice

In [2]:
sum = a + b
print(sum)
print(np.add(a, b))

print(a - b)
print(np.subtract(a, b))


print(a * b)
print(np.multiply(a, b))

print(a / b)
print(np.divide(a, b))

[[4 4 3 4]
 [3 2 3 3]
 [4 2 4 2]]
[[4 4 3 4]
 [3 2 3 3]
 [4 2 4 2]]
[[ 0  0 -1  0]
 [ 1  0 -1  1]
 [ 0  0  0  0]]
[[ 0  0 -1  0]
 [ 1  0 -1  1]
 [ 0  0  0  0]]
[[4 4 2 4]
 [2 1 2 2]
 [4 1 4 1]]
[[4 4 2 4]
 [2 1 2 2]
 [4 1 4 1]]
[[1.  1.  0.5 1. ]
 [2.  1.  0.5 2. ]
 [1.  1.  1.  1. ]]
[[1.  1.  0.5 1. ]
 [2.  1.  0.5 2. ]
 [1.  1.  1.  1. ]]


In [3]:
a + b * c

array([[4, 6, 3, 6],
       [3, 2, 5, 4],
       [4, 2, 4, 2]])

In [4]:
a ^ b

array([[0, 0, 3, 0],
       [3, 0, 3, 3],
       [0, 0, 0, 0]])

È possibile utilizzare operatori bitwise. Ad esempio, è possibile usare l'operatore `^` per l'xor bit a bit.

In [5]:
print(np.power(a, b))

print(np.sqrt(a))

n = np.random.randint(-4, -2, (2, 2))
print(n)
print(np.absolute(n))

[[4 4 1 4]
 [2 1 1 2]
 [4 1 4 1]]
[[1.41421356 1.41421356 1.         1.41421356]
 [1.41421356 1.         1.         1.41421356]
 [1.41421356 1.         1.41421356 1.        ]]
[[-4 -3]
 [-3 -4]]
[[4 3]
 [3 4]]


numpy ha una collezione molto approfondita di funzioni matematiche, che possono essere usate per le più comuni operazioni matematiche e trigonometriche. Esistono inoltre svariate costanti in numpy, come il pigreco. 

Le funzioni trigonometriche possono prendere in ingresso un singolo numero o un ndarray. In quest'ultimo caso restituiranno un array con il risultato della funzione trigonometrica applicato ad ogni singolo elemento. È inoltre possibile passare da gradi a radianti (e viceversa) con le funzioni `np.deg2rad()` e `np.rad2deg()`

In [6]:
print(np.pi)

print(np.sin(np.pi/4))
deg_angle = 45
print(np.sin(deg_angle * np.pi/180))
print(np.sin(np.deg2rad(deg_angle)))

print(np.deg2rad(180))
print(np.rad2deg(np.pi))

print(np.tan(np.pi/4))
print(np.tanh(np.pi/4))


3.141592653589793
0.7071067811865475
0.7071067811865475
0.7071067811865475
3.141592653589793
180.0
0.9999999999999999
0.6557942026326724


Ci sono le funzioni di arrotondamento: 
- round (arrotonda all'intero più vicino o al numero pari più vicino in caso la differenza fra il numero e l'intero più vicino sia di 0.5)
- floor (il "floor" di un numero `x` è l'intero `i` più grande tale che `i<=x` ) .
- ceil (il "ceil" di un numero `x` è l'intero `i` più piccolo tale che `i>=x` ) .
- truncate


In [7]:
c = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2])
print(c.dtype)
print(np.round(c))
print(np.floor(c))
print(np.ceil(c))
print(np.trunc(c))

float64
[-2. -2. -0.  0.  2.  2.  2.]
[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]
[-1. -1. -0.  0.  1.  1.  2.]


In [8]:
d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(d)

[[1 2 3]
 [4 5 6]]


Esistono delle funzioni che effettuano delle operazioni su tutti gli elementi di un array o solo su un asse:
- `prod`
- `sum`

In [9]:
p = np.prod(d)
print(p)

s = np.sum(d)
print(s)

print(np.prod(d, axis=0))
print(np.sum(d, axis=1))

720
21
[ 4 10 18]
[ 6 15]


Altre funzioni effettuano espressioni matematiche come l'esponenziale o il logaritmo naturale

In [10]:
print(np.exp(d))
print(np.log(d))
print(np.log10(d))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


## Test

