# Operatori logici

numpy è dotato di un'ampia gamma di operatori logici, che restituiscono cioè dei valori True o False sotto determinate condizioni. Cominciamo creando una nuova matrice di interi casuali utilizzando il generatore default_rng().

Il primo esempio è la funzione `all`, che restituisce `True` se tutti gli elementi di un array sono `True`. C'è da notare che in Python è possibile usare dei valori non booleani in contesto booleano. In questo caso si parla di valori _truthy_ e _falsy_. Sono valori _falsy_:
- la stringa vuota
- il numero 0
- una tupla/lista/dizionario vuoto
- `None`




In [1]:
import numpy as np
g = np.random.default_rng()

a = g.integers(-5, 5, (3, 2))

print(a)

[[-5  1]
 [-2  0]
 [ 1 -2]]


In [4]:
a.shape

(3, 2)

In [5]:
print(np.all(a))
print(np.all(a, axis=0).shape)
print(np.all(a, axis=0))
print(np.all(a, axis=1).shape)
print(np.all(a, axis=1))

print(np.any(a))

zeros = np.zeros((2,2))
print(zeros)
zeros[0,0] = 1
print(zeros)

print(np.any(zeros, axis=1))

False
(2,)
[ True False]
(3,)
[ True False  True]
True
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 0.]]
[ True False]


Un altro esempio di funzione che restituisce un risultato booleano è `any`, che restituisce `True` se almeno un elemento in una matrice (o su un asse) è pari a `True`.

## `where`


`np.where` è una funzione di NumPy che offre un modo efficace e flessibile per eseguire operazioni condizionali su array. È particolarmente utile per applicare condizioni logiche e selezionare elementi da uno o più array in base a tali condizioni. Ecco una panoramica dettagliata di come utilizzare `np.where` con alcuni esempi pratici.

### Sintassi di base

La sintassi di base di `np.where` è la seguente:

```phython
np.where(condizione, [x, y])
```

-   `condizione`: un array di booleans o una condizione che può essere applicata agli elementi di un array.
-   `x`: (opzionale) i valori da usare dove la condizione è vera.
-   `y`: (opzionale) i valori da usare dove la condizione è falsa.

### Utilizzo di base

#### Esempio 1: Individuare indici

Quando viene passato solo la condizione, `np.where` restituisce una tupla di array che indicano gli indici degli elementi che soddisfano la condizione.

```python
import numpy as np

a = np.array([1, 2, 3, 4, 5])
indices = np.where(a > 3)
print(indices)  # (array([3, 4]),)
```


#### Esempio 2: Selezionare elementi da array

Quando vengono passati tutti e tre i parametri, `np.where` restituirà un array in cui ogni elemento è preso da `x` se la condizione è vera, altrimenti da `y`.

```python
a = np.array([1, 2, 3, 4, 5])
b = np.where(a > 3, a, -a)
print(b)  # [-1 -2 -3  4  5]

```

#### Esempio 3: Sostituzione di valori

`np.where` può essere usato per sostituire valori in un array in base a una condizione.

```python
a = np.array([1, 2, 3, 4, 5])
b = np.where(a % 2 == 0, a * 2, a * -1)
print(b)  # [-1  4 -3  8 -5]

```

Ci sono poi altre funzioni element-wise che restituiscono `True` o `False`:
- `isnan` -> restituisce  True se l'elemento passato in input è NaN
- `isscalar` -> restituisce True se l'elemento passato in input è uno scalare
- `isreal` -> restituisce True se un numero è reale (anche se un numero complesso ha una parte immaginaria pari a 0)

In [3]:
print(np.isnan(np.nan))

b = g.choice([1, 0], (2, 2))
print(b)
print(np.isscalar(b))

print(np.isreal(
    np.array([3+0.5j, 3 + 0j])
))

True
[[0 1]
 [1 1]]
False
[False  True]


Ci sono poi le funzioni logiche che effettuano le classiche operazioni (and, or, xor, not) logiche applicandole in maniera element-wise.
- `logical_and`
- `logical_or`
- `logical_not`
- `logical_xor`

In [4]:
a = g.choice([True, False], (2, 2))
b = g.choice([True, False], (2, 2))


print(a, b)

print(np.logical_and(a, b))
print(np.logical_or(a, b))

[[False False]
 [False False]] [[False False]
 [ True False]]
[[False False]
 [False False]]
[[False False]
 [ True False]]


Esistono poi anche degli operatori di confronto fra ndarray:
- `array_equal`: restituisce True se due ndarray hanno stessa shape ed elementi
- `array_equiv`: restituisce True se due ndarray sono _consistenti_ e hanno gli stessi elementi. 

Due ndarray sono consistenti se hanno la stessa shape o se può essere fatta un'operazione di _broadcast_ per uniformare la shape. Il __broadcast__ è l'operazione di far "matchare" fra loro dimensioni di array con shape diverse per permettere l'esecuzione di operazioni sugli array (es. operazioni aritmetiche)


In [5]:
a = np.array([2, 3])
b = np.array([2, 3])
c = np.array([[2, 3], [2, 3]])

print(a)
print(b)

print(np.array_equal(a, b))
print(np.array_equiv(a, b))
print(np.array_equal(a, c))
print(np.array_equiv(a, c))

[2 3]
[2 3]
True
True
False
True


Altre funzioni element-wise sono le funzioni per il confronto. Queste funzioni hanno anche un corrispettivo con gli operatori di confronto "classici" come `>`, `<`, `>=`, `<=`, etc:
- `greater`
- `greater_equal`
- `less`
- `less_equal`
- `equal`
- `not_equal`

In [6]:
a = np.array([1, 2, 3, 4])
a_eq = np.array([1, 2, 3, 4])

print( a > a_eq)


[False False False False]



### Esercizio 1: Somma con Broadcasting

**Obiettivo:** Utilizzare il broadcasting per sommare una matrice e un vettore.

**Task:**

1.  Crea una matrice di interi casuali `a` di dimensioni $4 \times 3$ con valori compresi tra 1 e 10.
2.  Crea un vettore `b` di dimensioni $1 \times 3$ con valori compresi tra 1 e 10.
3.  Utilizza il broadcasting per sommare `a` e `b` e stampa il risultato.

In [11]:
g = np.random.default_rng()

a = g.integers(1, 11, (4, 3))
b = g.integers(1, 11, (3,))
print("Matrice a:\n", a)
print("Vettore b:\n", b)

print(a + b)

Matrice a:
 [[ 2  6  9]
 [ 8 10  8]
 [ 1  4  5]
 [ 1  9  5]]
Vettore b:
 [9 9 6]
[[11 15 15]
 [17 19 14]
 [10 13 11]
 [10 18 11]]



### Esercizio 2: Normalizzazione di Righe con Broadcasting

**Obiettivo:** Utilizzare il broadcasting per normalizzare le righe di una matrice.

**Task:**

1.  Crea una matrice di interi casuali `e` di dimensioni $3 \times 5$ con valori compresi tra 1 e 10.
2.  Calcola la somma di ogni riga e utilizza il broadcasting per dividere ogni elemento della matrice per la somma della sua riga.
3.  Stampa la matrice normalizzata.

In [13]:
g = np.random.default_rng()

a = g.integers(1, 11, (3, 5))

print(a)


[[ 7  1  8  3  4]
 [ 9 10  6  2  5]
 [ 1 10  1  9  3]]


In [18]:
# rows = a.sum(axis=1).reshape((3, -1))
rows = a.sum(axis=1, keepdims=True)

print(rows)

norm = a / rows

print(norm)

[[23]
 [32]
 [24]]
[[0.30434783 0.04347826 0.34782609 0.13043478 0.17391304]
 [0.28125    0.3125     0.1875     0.0625     0.15625   ]
 [0.04166667 0.41666667 0.04166667 0.375      0.125     ]]



### Esercizio 4: Trasformazione di Coordinate con Broadcasting

**Obiettivo:** Utilizzare il broadcasting per trasformare un insieme di punti in 2D.

**Task:**

1.  Crea una matrice `points` di dimensioni $5\times 2$ che rappresenta 5 punti in un piano 2D con valori compresi tra 0 e 10.
2.  Crea un vettore `translation` di dimensioni $1 \times 2$ che rappresenta una traslazione (dx, dy).
3.  Utilizza il broadcasting per applicare la traslazione a tutti i punti e stampa i nuovi punti trasformati.