L'indicizzazione degli ndarray e il loro slicing è una delle feature più interessanti degli ndarray, e sono quello che differenzia (al netto di tutte le funzioni matematiche/trigonometriche/logiche) effettivamente gli ndarray dalle liste Python. 

Il primo esempio di indicizzazione che vediamo è quello che fa uso di un altro array. Per il momento ci limitiamo all'uso di array monodimensionali.

In [4]:
import numpy as np

a = np.arange(-100, -200, -1)
print(a)

[-100 -101 -102 -103 -104 -105 -106 -107 -108 -109 -110 -111 -112 -113
 -114 -115 -116 -117 -118 -119 -120 -121 -122 -123 -124 -125 -126 -127
 -128 -129 -130 -131 -132 -133 -134 -135 -136 -137 -138 -139 -140 -141
 -142 -143 -144 -145 -146 -147 -148 -149 -150 -151 -152 -153 -154 -155
 -156 -157 -158 -159 -160 -161 -162 -163 -164 -165 -166 -167 -168 -169
 -170 -171 -172 -173 -174 -175 -176 -177 -178 -179 -180 -181 -182 -183
 -184 -185 -186 -187 -188 -189 -190 -191 -192 -193 -194 -195 -196 -197
 -198 -199]


È possibile usare un array di __indici__ per estrarre alcuni elementi da un array di partenza:

In [5]:
print(a[0])
print(a[-1])

print(a[np.array([4, 5, 6])])

print(a[np.array([-20, 10, 0])])

-100
-199
[-104 -105 -106]
[-180 -110 -100]


È possibile anche usare degli indici negativi (ricordando che l'indice negativo -1 corrisponde all'ultimo elemento di un array, -2 al penultimo, -3 al terzultimo etc etc)

## Slicing di base

Di norma, lo slicing di un array è nella forma `x[index]`, dove `x` è l'array e `index` uno fra questi 3 elementi:
- un numero intero
- un oggetto nella forma `start:stop:step`
- una tupla di oggetti slice e interi

In [6]:
print(a[10:100])
print(a[10:100:2])

print(a[0:-40:10])

[-110 -111 -112 -113 -114 -115 -116 -117 -118 -119 -120 -121 -122 -123
 -124 -125 -126 -127 -128 -129 -130 -131 -132 -133 -134 -135 -136 -137
 -138 -139 -140 -141 -142 -143 -144 -145 -146 -147 -148 -149 -150 -151
 -152 -153 -154 -155 -156 -157 -158 -159 -160 -161 -162 -163 -164 -165
 -166 -167 -168 -169 -170 -171 -172 -173 -174 -175 -176 -177 -178 -179
 -180 -181 -182 -183 -184 -185 -186 -187 -188 -189 -190 -191 -192 -193
 -194 -195 -196 -197 -198 -199]
[-110 -112 -114 -116 -118 -120 -122 -124 -126 -128 -130 -132 -134 -136
 -138 -140 -142 -144 -146 -148 -150 -152 -154 -156 -158 -160 -162 -164
 -166 -168 -170 -172 -174 -176 -178 -180 -182 -184 -186 -188 -190 -192
 -194 -196 -198]
[-100 -110 -120 -130 -140 -150]


Vediamo anche lo slicing di oggetti multidimensionali. Per un array a N dimensioni possiamo avere fino ad N oggetti di slicing. Possiamo inoltre usare l'operatore ellpisis per non specificare tutte le dimensioni qualora dovessimo operare lo slicing solo su un asse. 

In [7]:
b = np.arange(-300, -200).reshape(5, 20)
print(b)

[[-300 -299 -298 -297 -296 -295 -294 -293 -292 -291 -290 -289 -288 -287
  -286 -285 -284 -283 -282 -281]
 [-280 -279 -278 -277 -276 -275 -274 -273 -272 -271 -270 -269 -268 -267
  -266 -265 -264 -263 -262 -261]
 [-260 -259 -258 -257 -256 -255 -254 -253 -252 -251 -250 -249 -248 -247
  -246 -245 -244 -243 -242 -241]
 [-240 -239 -238 -237 -236 -235 -234 -233 -232 -231 -230 -229 -228 -227
  -226 -225 -224 -223 -222 -221]
 [-220 -219 -218 -217 -216 -215 -214 -213 -212 -211 -210 -209 -208 -207
  -206 -205 -204 -203 -202 -201]]


In [8]:
print(b[0:2,0:20])
print(b[0:2,0:10])

[[-300 -299 -298 -297 -296 -295 -294 -293 -292 -291 -290 -289 -288 -287
  -286 -285 -284 -283 -282 -281]
 [-280 -279 -278 -277 -276 -275 -274 -273 -272 -271 -270 -269 -268 -267
  -266 -265 -264 -263 -262 -261]]
[[-300 -299 -298 -297 -296 -295 -294 -293 -292 -291]
 [-280 -279 -278 -277 -276 -275 -274 -273 -272 -271]]


In [9]:
print(b[...,0:5])

[[-300 -299 -298 -297 -296]
 [-280 -279 -278 -277 -276]
 [-260 -259 -258 -257 -256]
 [-240 -239 -238 -237 -236]
 [-220 -219 -218 -217 -216]]


## Slicing avanzato

Si parla di slicing avanzato quando in `x[obj]` l'oggetto di slicing `obj` è:
- un array di interi o booleani
- una tupla con almeno un oggetto di tipo "sequence"
- un oggetto sequence non tupla



In [7]:
print(b)
print(b[b>=-250])

print(b[b%2==1])

[[-300 -299 -298 -297 -296 -295 -294 -293 -292 -291 -290 -289 -288 -287
  -286 -285 -284 -283 -282 -281]
 [-280 -279 -278 -277 -276 -275 -274 -273 -272 -271 -270 -269 -268 -267
  -266 -265 -264 -263 -262 -261]
 [-260 -259 -258 -257 -256 -255 -254 -253 -252 -251 -250 -249 -248 -247
  -246 -245 -244 -243 -242 -241]
 [-240 -239 -238 -237 -236 -235 -234 -233 -232 -231 -230 -229 -228 -227
  -226 -225 -224 -223 -222 -221]
 [-220 -219 -218 -217 -216 -215 -214 -213 -212 -211 -210 -209 -208 -207
  -206 -205 -204 -203 -202 -201]]
[-250 -249 -248 -247 -246 -245 -244 -243 -242 -241 -240 -239 -238 -237
 -236 -235 -234 -233 -232 -231 -230 -229 -228 -227 -226 -225 -224 -223
 -222 -221 -220 -219 -218 -217 -216 -215 -214 -213 -212 -211 -210 -209
 -208 -207 -206 -205 -204 -203 -202 -201]
[-299 -297 -295 -293 -291 -289 -287 -285 -283 -281 -279 -277 -275 -273
 -271 -269 -267 -265 -263 -261 -259 -257 -255 -253 -251 -249 -247 -245
 -243 -241 -239 -237 -235 -233 -231 -229 -227 -225 -223 -221 -219 -217
 -215 

In [9]:
b = np.array([[5,5], [4,4],[1, 5], [16, 1]])
print(b)

sum_x_axis = b.sum(axis=1)
print(sum_x_axis)


[[ 5  5]
 [ 4  4]
 [ 1  5]
 [16  1]]
[10  8  6 17]



### Esercizio 1: Slicing di Sottomatrici

**Obiettivo:** Estrarre sottomatrici specifiche utilizzando slicing.

**Task:**

1.  Crea una matrice di interi casuali `a` di dimensioni $6 \times 6$ con valori compresi tra 1 e 20.
2.  Utilizza lo slicing per estrarre e stampare le seguenti sottomatrici:
    -   I primi 3 elementi delle prime 2 righe.
    -   Gli ultimi 2 elementi delle ultime 3 righe.
    -   La sottomatrice centrale di dimensioni $2\times2$.

In [24]:
# Esercizio 1

g = np.random.default_rng()

a = g.integers(1, 20, (6, 6))

print(a)
print(a.shape)

[[ 3  5  6  5 16  5]
 [10 14 14  8 14 15]
 [ 3  7 17  3 18  2]
 [ 8  2  6 14 15 19]
 [ 4 18  9 19  8 11]
 [15 14 17  8 17 19]]
(6, 6)


In [33]:
a.argsort(axis=None).reshape(6, -1)

array([[17, 19, 15, 12,  0, 24],
       [ 5,  1,  3,  2, 20, 13],
       [ 9, 28, 18, 33, 26,  6],
       [29, 21,  8,  7, 31, 10],
       [30, 11, 22,  4, 34, 14],
       [32, 16, 25, 23, 27, 35]])


### Esercizio 2: Slicing di Righe e Colonne Specifiche

**Obiettivo:** Selezionare righe e colonne specifiche di una matrice utilizzando slicing.

**Task:**

1.  Crea una matrice di interi casuali `c` di dimensioni $7 \times 7 $ con valori compresi tra 1 e 25.
2.  Utilizza lo slicing per estrarre e stampare le seguenti righe e colonne:
    -   La terza e la quinta riga.
    -   La seconda e l'ultima colonna.