Sappiamo già che ogni ndarray ha una `shape`, che sarebbe una tupla contenente il numero di elementi per ogni asse. 

In [1]:
import numpy as np

x = np.random.randint(1, 4)
y = np.random.randint(1, 4)
z = np.random.randint(1, 4)

a = np.ones((x, y, z))

print(a)
print(a.shape)

[[[1. 1.]]

 [[1. 1.]]]
(2, 1, 2)


In [2]:
import numpy as np

x = np.random.randint(1, 4)
y = np.random.randint(1, 4)
z = np.random.randint(1, 4)

a = np.ones((x, y, z))

print(a)
print(a.shape)

[[[1.]]

 [[1.]]]
(2, 1, 1)


numpy dà la possibilità di cambiare la shape di un array, a condizione che il numero di elementi della vecchia shape sia uguale al numero di elementi della nuova shape. La funzione (chainabile) è `reshape`

In [3]:
a = np.arange(30, 42).reshape(3, 4)
print(a)

print(a.reshape(2, 3, 2))

print(a.reshape(1, 2, 7))

[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]
[[[30 31]
  [32 33]
  [34 35]]

 [[36 37]
  [38 39]
  [40 41]]]


ValueError: cannot reshape array of size 12 into shape (1,2,7)

È possibile specificare un ordinamento c-like o fortran-like specificando il parametro "order":

In [4]:
print(a.reshape((3, 4), order="f"))

[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


numpy ci dà la possibilità di effettuare un reshape ad un array monodimensionale con la funzione `flatten`

In [5]:
print(type(a.flatten()))
print(a.flatten())

<class 'numpy.ndarray'>
[30 31 32 33 34 35 36 37 38 39 40 41]


Anche in questo caso è possibile specificare un parametro `order`:



In [6]:
print(a.transpose())
print(a.T)

[[30 34 38]
 [31 35 39]
 [32 36 40]
 [33 37 41]]
[[30 34 38]
 [31 35 39]
 [32 36 40]
 [33 37 41]]


Un'operazione molto utilizzata di reshape è l'operazione di trasposizione di un array multidimensionale. Consiste semplicemente nello scambiare le dimensioni per cui una matrice 4x3 diventerebbe una matrice 3x4. 

In [7]:
b = a.reshape(3, 2, 2)
print(b)
print(b.shape)

print(b.transpose().shape, b.transpose())

print(np.transpose(b, axes=(1, 2, 0)).shape)

[[[30 31]
  [32 33]]

 [[34 35]
  [36 37]]

 [[38 39]
  [40 41]]]
(3, 2, 2)
(2, 2, 3) [[[30 34 38]
  [32 36 40]]

 [[31 35 39]
  [33 37 41]]]
(2, 2, 3)


In [8]:
a = np.random.rand(2, 3, 4)
print(a)
print(a.shape)  # (2, 3, 4)

b = np.transpose(a, (1, 0, 2))
print(b)
print(b.shape)  # (3, 2, 4)

[[[0.30896747 0.97854277 0.29912542 0.63289889]
  [0.1386723  0.06952958 0.58211511 0.29206023]
  [0.20345396 0.56108635 0.61104654 0.47802218]]

 [[0.49748224 0.43201702 0.80668787 0.19717687]
  [0.43829695 0.76196074 0.26990871 0.62751437]
  [0.35976404 0.44663896 0.89604937 0.69005732]]]
(2, 3, 4)
[[[0.30896747 0.97854277 0.29912542 0.63289889]
  [0.49748224 0.43201702 0.80668787 0.19717687]]

 [[0.1386723  0.06952958 0.58211511 0.29206023]
  [0.43829695 0.76196074 0.26990871 0.62751437]]

 [[0.20345396 0.56108635 0.61104654 0.47802218]
  [0.35976404 0.44663896 0.89604937 0.69005732]]]
(3, 2, 4)



Quando usiamo `np.transpose(a, (1, 0, 2))`, stiamo dicendo a NumPy di scambiare l'asse 0 con l'asse 1, mentre l'asse 2 rimane lo stesso. Quindi, se `a` ha la forma `(2, 3, 4)`, l'array trasposto `b` avrà la forma `(3, 2, 4)`.

Per visualizzare chiaramente il cambiamento, consideriamo gli indici di esempio:

-   Indice originale: `a[i, j, k]`
-   Indice trasposto: `b[j, i, k]`

In [9]:
a = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],

              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])
print("Array originale:\n", a)
print("Shape originale:", a.shape)  # (2, 3, 4)

Array originale:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape originale: (2, 3, 4)


In [10]:
b = np.transpose(a, (1, 0, 2))
print("Array trasposto:\n", b)
print("Shape trasposto:", b.shape)  # (3, 2, 4)


Array trasposto:
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
Shape trasposto: (3, 2, 4)



### Visualizzazione del cambiamento

Vediamo come gli elementi si spostano:

-   Elemento `a[0, 0, 0]` (valore `0`) diventa `b[0, 0, 0]`
-   Elemento `a[0, 1, 0]` (valore `4`) diventa `b[1, 0, 0]`
-   Elemento `a[0, 2, 0]` (valore `8`) diventa `b[2, 0, 0]`
-   Elemento `a[1, 0, 0]` (valore `12`) diventa `b[0, 1, 0]`
-   Elemento `a[1, 1, 0]` (valore `16`) diventa `b[1, 1, 0]`
-   Elemento `a[1, 2, 0]` (valore `20`) diventa `b[2, 1, 0]`
-   ... e così via per gli altri elementi.

In generale, ogni elemento `a[i, j, k]` viene spostato in `b[j, i, k]`.

### Esercizio 1: Reshape e Somma di Matrici

**Obiettivo:** Utilizzare `reshape` per riorganizzare una matrice e sommare con un vettore.

**Task:**

1.  Crea una matrice `a` di dimensioni $12$ con valori compresi tra 1 e 12.
2.  Modifica lo shape di `a` in una matrice $3 \times 4$.
3.  Crea un vettore `b` di dimensioni $4$ con valori compresi tra 1 e 4.
4.  Utilizza il broadcasting per sommare `a` e `b` e stampa il risultato.


### Esercizio 2: Combinazione di Reshape, Transpose e Flatten

**Obiettivo:** Utilizzare `reshape`, `transpose` e `flatten` in sequenza per trasformare una matrice.

**Task:**

1.  Crea una matrice `f` di dimensioni $4 \times 4$ con valori compresi tra 1 e 16.
2.  Modifica lo shape di `f` in una matrice $2 \times 8$.
3.  Trasponi la matrice `f_reshaped`.
4.  Utilizza `flatten` per appiattire la matrice trasposta `f_T`.
5.  Stampa il risultato finale.