È possibile unire diversi array numpy seguendo diverse modalità che permettono di poter comporli a seconda delle nostre necessità

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([3, 4, 5])


print(np.concatenate([a, b]))

[1 2 3 3 4 5]


È importante notare che la concatenate è esguita direttamente in C. Le altre funzioni che vedremo, invece, sono script Python che internamente richiamano la concatenate con gli opportuni parametri.
prendiamo array bidimensionali e vediamo come funzionano le concatenazioni sfruttando più assi (più dimensioni). Di default la concatenazione viene fatta sull'asse 0 (l'asse y), ma è possibile specificare un asse diverso con il parametro nominale `axis`


In [2]:
array_1 = np.array([
    [1],
    [2],
    [3],
])

array_2 = np.array([
    [3],
    [4],
    [5],
])

print(array_1.shape, array_2.shape)

c = np.concatenate([array_1, array_2])

print(c.shape)
print(c)

(3, 1) (3, 1)
(6, 1)
[[1]
 [2]
 [3]
 [3]
 [4]
 [5]]


In [3]:
c_x = np.concatenate([array_1, array_2], axis=1)
print(c_x.shape)
print(c_x)

(3, 2)
[[1 3]
 [2 4]
 [3 5]]


In entrambi i casi abbiamo le funzioni di utility `hstack` e `vstack` con le quali otteniamo lo stesso risultato:

In [4]:
c_x = np.hstack((array_1, array_2))
c_y = np.vstack((array_1, array_2))
print(c_x)
print(c_y)

[[1 3]
 [2 4]
 [3 5]]
[[1]
 [2]
 [3]
 [3]
 [4]
 [5]]


È possibile aggiungere un asse alla concatenazione di due ndarray usando la funzione `stack`. In questo modo aumentiamo la dimensionalità di 1 dimensione. Anche qui possiamo decidere su che asse effettuare questa concatenazione.

In [5]:
c = np.stack([array_1, array_2], axis=1)
print(c.shape)
print(c)

(3, 2, 1)
[[[1]
  [3]]

 [[2]
  [4]]

 [[3]
  [5]]]


In [6]:
grid = np.column_stack((array_1, array_2))
print(grid)

[[1 3]
 [2 4]
 [3 5]]


È possibile usare `column_stack` per unire più vettori (array monodimensionali) in una matrice, un po' come se avessimo una serie di rilevazioni su diverse feature che stiamo osservando e vogliamo riunirle in un unico elenco dove sulle righe abbiamo i singoli esempi/rilevazioni e sulle colonne riportiamo le singole feature/caratteristiche

`append` "appende" il secondo array che passiamo dopo il primo e ritorna un unico array contenente entrambi

In [7]:
d = np.append(array_1, array_2)
print(d.shape)
print(d)

(6,)
[1 2 3 3 4 5]


È possibile anche effettuare delle operazioni tipiche dell'insiemistica come unione e intersezione:

In [8]:
print(np.intersect1d(array_1, array_2))
print(np.union1d(array_1, array_2))

[3]
[1 2 3 4 5]


e verificare element-wise la presenza di elementi in array diversi:

In [9]:
sub_array_1 = [-1, 2, 3]

print(array_1)

[[1]
 [2]
 [3]]


In [10]:
print(np.isin(sub_array_1, array_1))

[False  True  True]


In [11]:
print(np.repeat(1, 10).reshape(2, -1))

[[1 1 1 1 1]
 [1 1 1 1 1]]
