È possibile suddividere un array in sotto-array utilizzando le funzioni di split. Esse restituiscono una lista nativa Python formata da ndarray.

La funzione split se usata con vettori monodimensionali accetta l'ndarray da splittare come primo argomento e il numero di elementi in cui dividere la struttura dati.

In [1]:
import numpy as np

In [2]:
a = np.arange(30)

sub_arrays = np.split(a, 3)

print(a)

print(type(sub_arrays))

for array in sub_arrays:
    print(type(array))
    print(len(array), array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'list'>
<class 'numpy.ndarray'>
10 [0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
10 [10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
10 [20 21 22 23 24 25 26 27 28 29]


Ecco un esempio di utilizzo con le matrici. Notiamo che gli elementi della lista sono _ancora_ delle matrici, di dimensione 1x3:

In [3]:
a = np.array([
    [1, 10, 100],
    [2, 20, 200]
])

sub = np.split(a, 2)

print(type(sub))

for ar in sub:
    print(type(ar))
    print(ar.shape)
    print(ar, "\n")

<class 'list'>
<class 'numpy.ndarray'>
(1, 3)
[[  1  10 100]] 

<class 'numpy.ndarray'>
(1, 3)
[[  2  20 200]] 



"vsplit" (vertical split) viene utilizzata per fare uno split sull'asse y. 

In [4]:
a = np.array([
    [1, 10, 100],
    [2, 20, 200],
    [3, 30, 300],
    [4, 40, 400]
])

array_col = np.split(a, 3, axis=1)

for ar in array_col:
    print(ar)
    


[[1]
 [2]
 [3]
 [4]]
[[10]
 [20]
 [30]
 [40]]
[[100]
 [200]
 [300]
 [400]]
[[1]
 [2]
 [3]
 [4]]
[[10]
 [20]
 [30]
 [40]]
[[100]
 [200]
 [300]
 [400]]


Risultato analogo si può ottenere con hsplit (split orizzontale)

In [ ]:
array_col = np.hsplit(a, 3)

for ar in array_col:
    print(ar)

`array_split` funziona in maniera analoga a `split`, senza tuttavia sollevare eccezioni qualora non passassimo un numero di parti non perfettamente proporzionale all'array di partenza:

In [5]:
a = np.array([
    [1, 10, 100],
    [2, 20, 200]
])


print(a)

sub = np.array_split(a, 3)

for ar in sub:
    print(ar.shape)
    print(ar)

[[  1  10 100]
 [  2  20 200]]
(1, 3)
[[  1  10 100]]
(1, 3)
[[  2  20 200]]
(0, 3)
[]
