Quando si manipolano gli array, capita che ci sia il bisogno di copiare intere strutture dati in un array. È bene capire bene quali tipi di copia ci sono in numpy.

## Nessuna copia

Le assegnazioni dirette non fanno alcuna copia dei dati. Python passa questi oggetti per reference:


In [1]:
import numpy as np

a = np.arange(10)
print(a)

b = a

print(id(b))
print(id(a))

b.shape = 2,5

print(a)

b[0] = 100
print(a)

print(b is a)

[0 1 2 3 4 5 6 7 8 9]
4381012592
4381012592
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 100 100 100 100]
 [  5   6   7   8   9]]
True


## view

Il metodo `view` crea una copia "superficiale" dell'array:

In [2]:
a = np.arange(10)
print(a)

b = a.view()

print(id(a) == id(b))

print(a is b)

b.shape = 2,5

print(b.shape, a.shape)

b[0, 0] = 1000

print(a)

[0 1 2 3 4 5 6 7 8 9]
False
False
(2, 5) (10,)
[1000    1    2    3    4    5    6    7    8    9]


## deep copy

È possibile ottenere una copia deep di un ndarray usando il metodo `copy`

In [3]:
a = np.arange(10)

print(a)
v = a.view()
b = a.copy()

print(a is b)
print(id(a), id(b))

print(a.base)
print(v.base)
print(b.base)

b[0] = 1000

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
False
4381013936 4381010768
None
[0 1 2 3 4 5 6 7 8 9]
None
[0 1 2 3 4 5 6 7 8 9]
[1000    1    2    3    4    5    6    7    8    9]


È possibile anche usare la funzione `copyto` che prende in input 2 ndarray, la destinazione e la sorgente dei dati:



In [4]:
a = np.arange(0, 24, 2).reshape(2, 6)
b = np.zeros

print(a)

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]]
