Numpy mette a disposizione il metodo `sort` grazie al quale possiamo ordinare un array :

In [1]:
import numpy as np

a = np.array([4, 1, 20, 11])

print(np.sort(a))

[ 1  4 11 20]


In [2]:
a = np.array(["Philip", "Frank", "Anthony"])

print(np.sort(a))

['Anthony' 'Frank' 'Philip']


In [3]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(arr)

print(np.sort(arr))

print(np.sort(arr, axis=0))


print(np.sort(arr, axis=None))

[[3 2 4]
 [5 0 1]]
[[2 3 4]
 [0 1 5]]
[[3 0 1]
 [5 2 4]]
[0 1 2 3 4 5]


È possibile specificare come parametro nominale `axis`. Se pari a `None` l'array verrà _flattened_ e poi verrà ordinato. Se pari a 1 l'ordinamento verrà effettuato sull'asse y:

È possibile inoltre usare la funzione di sort anche quando gli array sono formati da tipi complessi

In [4]:
dtype = [
    ("name", "S10"),
    ("rank", float),
    ("age", int)
]

values = [
    ("Philip", 3, 41),
    ("Viktor", 6, 35),
    ("Andrew", 1, 25),
    ("Jackie", 2, 41),
    ("Johnny", 5, 36),
    ("Thomas", 4, 35),
]

a = np.array(values, dtype=dtype)
print(type(a))
print(a)

print(np.sort(a, order=["name", "rank"]))
print(np.sort(a, order=["rank", "age", "name"]))

<class 'numpy.ndarray'>
[(b'Philip', 3., 41) (b'Viktor', 6., 35) (b'Andrew', 1., 25)
 (b'Jackie', 2., 41) (b'Johnny', 5., 36) (b'Thomas', 4., 35)]
[(b'Andrew', 1., 25) (b'Jackie', 2., 41) (b'Johnny', 5., 36)
 (b'Philip', 3., 41) (b'Thomas', 4., 35) (b'Viktor', 6., 35)]
[(b'Andrew', 1., 25) (b'Jackie', 2., 41) (b'Philip', 3., 41)
 (b'Thomas', 4., 35) (b'Johnny', 5., 36) (b'Viktor', 6., 35)]


È inoltre possibile effettuare delle operazioni di filtraggio semplici o complesse:


In [5]:
num = np.arange(40, 120, 3)
print(num.size)
print(num)

print(num[num%2==0])

filtered = []


for element in num:
    if element % 2 == 0:
        filtered.append(True)
    else: 
        filtered.append(False)
        
        
print(filtered)

27
[ 40  43  46  49  52  55  58  61  64  67  70  73  76  79  82  85  88  91
  94  97 100 103 106 109 112 115 118]
[ 40  46  52  58  64  70  76  82  88  94 100 106 112 118]
[True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
