Numpy è dotato di una serie di utilissime funzioni statistiche:
- `amin`/`amax`: restituiscono il valore minimo/massimo di un array o di un asse specificato
- `mean`: calcola la media degli elementi di un array o su un asse specifico
- `median`: calcola la mediana degli elementi di un array o su un asse specifico
- `std`: calcola la deviazione standard degli elementi di un array o su un asse specifico (la radice della varianza)
- `var`: calcola la varianza degli elementi di un array o su un asse specifico (il quadrato della dev. std)
- `average`: calcola la media pesata degli elementi di un array o su un asse specifico, prendendo anche in input una struttura dati che contenga i pesi
- `ptp`: utile per calcolare i range di valori lungo un asse di un array (peak to peak)
- `percentile`: utile per calcolare il percentile, ovvero il minimo valore sotto al quale ricade una data percentuale degli altri elementi sotto osservazione

In [1]:
import numpy as np

arr = np.array([[1, 23, 78], [98, 60, -2], [79, 25, 48]])

print(arr)

print(np.amin(arr))
print(np.amin(arr, axis=0))

print(np.amax(arr))

[[ 1 23 78]
 [98 60 -2]
 [79 25 48]]
-2
[ 1 23 -2]
98


In [2]:
print(arr)

print(np.mean(arr))

print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[[ 1 23 78]
 [98 60 -2]
 [79 25 48]]
45.55555555555556
[59.33333333 36.         41.33333333]
[34.         52.         50.66666667]


In [3]:
print(arr)
print(np.median(arr))
print(np.median(arr, axis=1))

[[ 1 23 78]
 [98 60 -2]
 [79 25 48]]
48.0
[23. 60. 48.]


In [4]:
print(np.std(arr))

33.85298644666412


In [5]:
print(np.var(arr,axis=1))

[1048.66666667 1698.66666667  489.55555556]


la funzione `percentile` richiede 3 argomenti:
- l'array sul quale misurare il percentile
- il percentile da considerare sull'array compreso fra 0 e 100 (es. percentile = 50 è il percentile che lascia alla sua sinistra il 50% dei valori della distribuzione)
- l'asse su cui calcolare il valore del percentile

In [6]:
c = np.array([10, 10, 20, 30, 40, 20, 10, 10, 10, 20])

print(c)

print(np.percentile(c, 50))

[10 10 20 30 40 20 10 10 10 20]
15.0
